// Generated by https://quicktype.io

export interface Animal {
    id:          string;
    name:        string;
    description: string;
    isHealth:    boolean;
    imageUrl:     string;
    diseases:    Disease[];
}

export interface Disease {
    id:   number;
    name: string;
}
